MarkerClusterer/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarkerClusterer.Controllers
{
    public class ConfigurationController : Controller
    {
        public ActionResult Reports()
        {
            return View();
        }

        public ActionResult ParamsReports()
        {
            return View();
        }

        public ActionResult Alarms()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View();
        }

        public ActionResult Documents()
        {
            return View();
        }
    }
}

MarkerClusterer/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MarkerClusterer.Models;

namespace MarkerClusterer.Controllers
{
    public class ItemsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Items
        public async Task<ActionResult> Index()
        {
            return View(await db.Items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)            
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Item item = await db.Items.FindAsync(id);
            if (item == null)            
                return HttpNotFound();
            
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.Parents = new SelectList(db.Items.ToList(), "Id", "Name");

            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Name,Nodo,Latitude,Longitude,ParentId")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Parents = new SelectList(db.Items.ToList(), "Id", "Name", item.ParentId);

            return View(item);
        }

        
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)            
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Item item = await db.Items.FindAsync(id);
            ViewBag.Parents = new SelectList(db.Items.ToList(), "Id", "Name", item.ParentId);
            if (item == null)            
                return HttpNotFound();
            
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,Name,Nodo,Latitude,Longitude,ParentId")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Parents = new SelectList(db.Items.ToList(), "Id", "Name", item.ParentId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)            
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Item item = await db.Items.FindAsync(id);
            if (item == null)            
                return HttpNotFound();
            
            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (db.Items.Where(x => x.ParentId == id).Count() == 0)
            {
                Item item = await db.Items.FindAsync(id);
                db.Items.Remove(item);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "This item have childrens items and can not errase";
                return RedirectToAction("Delete", new { id = id});
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)            
                db.Dispose();
            
            base.Dispose(disposing);
        }
    }
}

MarkerClusterer/Controllers/NotificationController.cs
using MarkerClusterer.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarkerClusterer.Controllers
{
    public class NotificationController : Controller
    {
        // GET: Notification
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult AllToast()
        {
            this.AddToastMessage("MENSAJE DE ERROR", "Mensaje de error", ToastType.Error);
            this.AddToastMessage("Mensaje Informativo", "Mensaje informativo", ToastType.Info);
            this.AddToastMessage("Mensaje Exitoso", "Mensaje exitoso", ToastType.Success);
            this.AddToastMessage("Mensaje de Advertencia", "Mensaje de Advertencia", ToastType.Warning);
            return RedirectToAction("Index");
        }
        public ActionResult Error()
        {
            this.AddToastMessage("MENSAJE DE ERROR", "Mensaje de error", ToastType.Error);
            return RedirectToAction("Index");
        }
        public ActionResult Info()
        {
            this.AddToastMessage("Mensaje Informativo", "Mensaje informativo", ToastType.Info);
            return RedirectToAction("Index");
        }
        public ActionResult Success()
        {
            this.AddToastMessage("Mensaje Exitoso", "Mensaje exitoso", ToastType.Success);
            return RedirectToAction("Index");
        }
        public ActionResult Warning()
        {
            this.AddToastMessage("Mensaje de Advertencia", "Mensaje de Advertencia", ToastType.Warning);
            return RedirectToAction("Index");
        }
    }
}

MarkerClusterer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frontera Energy | Indicadores MIA</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/toastr.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/toastr.min.js"></script>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Frontera Energy", "Navigation", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Navigation","Home",new { id = 3 })">Home</a></li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Gestionar Nodos <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Create","Items")">Adicionar Nodo</a></li>
                            <li><a href="@Url.Action("Index","Items")">Lista de Nodos</a></li>
                            <li><a href="@Url.Action("Menu","Home", new { id = 3 })">Ver MENU</a></li>
                            <li><a href="@Url.Action("GoogleMaps","Home")">Nodos en Google Maps</a></li>
                        </ul>
                    </li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Configuracion <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Reports","Configuration")" >Gestion de Reportes</a></li>
                            <li><a href="@Url.Action("ParamsReports","Configuration")">Parametrizacion de Reportes</a></li>
                            <li><a href="@Url.Action("Alarms","Configuration")">Gestion de Alarmas</a></li>
                            <li><a href="@Url.Action("Users","Configuration")">Gestion de Usuarios</a></li>
                            <li><a href="@Url.Action("Documents","Configuration")">Gestion de Documentos</a></li>
                        </ul>
                    </li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Notificaciones <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Panel de Notificaciones", "Index", "Notification")</li>
                            <li>@Html.ActionLink("Notificacion de Error", "Error","Notification")</li>
                            <li>@Html.ActionLink("Notificacion Exitosa", "Success", "Notification")</li>
                            <li>@Html.ActionLink("Notificacion de Informacion", "Info", "Notification")</li>
                            <li>@Html.ActionLink("Notificacion de Advertencia", "Warning", "Notification")</li>
                            <li>@Html.ActionLink("Todas las notificaciones", "AllToast", "Notification")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>    
    <div class="container body-content">
        <div class="row">
            <div><br /><br /><br /></div>
        </div>
        <div class="row">
            @RenderBody()
        </div>
        @Html.Partial("_Toastr")
    </div>
    <hr />
    <footer>
        <center>
            <p>&copy; @DateTime.Now.Year - Developed by - <a href="https://www.indracompany.com/" target="_blank">Indra Company</a></p>
        </center>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MarkerClusterer/Views/Shared/_Toastr.cshtml
@using MarkerClusterer.Helpers
@if (TempData.ContainsKey("Toastr"))
{
    Toastr toastr = TempData["Toastr"] as Toastr;
    @ToastrBuilder.ShowToastMessages(toastr);
}